
export const CARS_LOADING = "CARS_LOADING";
export const CARS_FALIED = "CARS_FALIED";
export const ADD_CARS = "ADD_CARS";
export const CAR_ADD_FAILED = "CAR_ADD_FAILED";
export const CAR_IS_ADDED = "CAR_IS_ADDED";
export const CAR_TO_UPDATE = "CAR_TO_UPDATE"
export const CAR_IS_UPDATED = "CAR_IS_UPDATED"

export const BRANDS_LOADING = "BRANDS_LOADING";
export const BRANDS_FALIED = "BRANDS_FALIED";
export const ADD_BRANDS = "ADD_BRANDS";
export const BRAND_ADD_FAILED = "BRAND_ADD_FAILED";
export const BRAND_IS_ADDED = "BRAND_IS_ADDED";
export const BRAND_TO_UPDATE = "BRAND_TO_UPDATE"
export const BRAND_IS_UPDATED = "BRAND_IS_UPDATED"



export const CATEGORIES_LOADING = "CATEGORIES_LOADING";
export const CATEGORIES_FALIED = "CATEGORIES_FALIED";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const CATEGORY_ADD_FAILED = "CATEGORY_ADD_FAILED";
export const CATEGORY_IS_ADDED = "CATEGORY_IS_ADDED";
export const CATEGORY_IS_UPDATED = "CATEGORY_IS_UPDATED"
export const CATEGORY_TO_UPDATE = "CATEGORY_TO_UPDATE"

export const COMPANIES_LOADING = "COMPANIES_LOADING";
export const COMPANIES_FALIED = "COMPANIES_FALIED";
export const ADD_COMPANIES = "ADD_COMPANIES";
export const COMPANY_ADD_FAILED = "COMPANY_ADD_FAILED";
export const COMPANY_IS_ADDED = "COMPANY_IS_ADDED";
export const COMPANY_TO_UPDATE = "COMPANY_TO_UPDATE";
export const COMPANY_IS_UPDATED = "COMPANY_IS_UPDATED";

export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_FALIED = "DEPARTMENTS_FALIED";
export const ADD_DEPARTMENTS = "ADD_DEPARTMENTS";
export const DEPARTMENT_ADD_FAILED = "DEPARTMENT_ADD_FAILED";
export const DEPARTMENT_IS_ADDED = "DEPARTMENT_IS_ADDED";
export const DEPARTMENT_IS_UPDATED = "DEPARTMENT_IS_UPDATED";
export const DEPARTMENT_TO_UPDATE = "DEPARTMENT_TO_UPDATE"

export const EMPLOYEES_LOADING = "EMPLOYEES_LOADING";
export const EMPLOYEES_FALIED = "EMPLOYEES_FALIED";
export const ADD_EMPLOYEES = "ADD_EMPLOYEES";
export const EMPLOYEE_ADD_FAILED = "EMPLOYEE_ADD_FAILED";
export const EMPLOYEE_IS_ADDED = "EMPLOYEE_IS_ADDED";

export const QUOTAS_LOADING = "QUOTAS_LOADING";
export const QUOTAS_FALIED = "QUOTAS_FALIED";
export const ADD_QUOTAS = "ADD_QUOTAS";
export const QUOTA_ADD_FAILED = "QUOTA_ADD_FAILED";
export const QUOTA_IS_ADDED = "QUOTA_IS_ADDED";
export const QUOTA_IS_UPDATED = "QUOTA_IS_UPDATED";
export const QUOTA_TO_UPDATE = "QUOTA_TO_UPDATE"

export const IMAGE_IS_ADDED="IMAGE_IS_ADDED"
export const IMAGE_ADD_FAILED="IMAGE_ADD_FAILED"